### ISSUE TITLE
coveralls coverage report for files is broken

### ISSUE THREAD

**Issue by josef-pkt** [nipy/nipy#311]
https://coveralls.io/files/151761134

```
The file "/usr/local/lib/python2.7/dist-packages/nipy/core/api.py" isn't available on GitHub. Either it's been removed, or the repo root directory needs to be updated.
```

Since statsmodels has the same pattern for travis.yml file as nipy.
https://github.com/statsmodels/statsmodels/issues/1502

seems like we need to update

nipype which doesn't pretend to be erlang works fine

**Comment by matthew-brett** [comment]
I believe coverage is working correctly now - closing.
