### ISSUE TITLE
nipy.labs.group.permutation_test two-sampled data isn't correctly permuted

### ISSUE THREAD

**Issue by jwirsich** [nipy/nipy#323]
In file nipy.labs.group.permutation_test:
Function calibrate statistics are calculated on original data for the two sample case (line 81)
-> tmax statistic always constant -> tmax corrected pvalue is wrong.
Solution: the two sampled test should be run for permuted data.

**Comment by matthew-brett** [comment]
Bertrand - should this go in as a fix?

**Comment by matthew-brett** [comment]
Appears to be closed by #347
