### ISSUE TITLE
plot_map error with numpy 1.9

### ISSUE THREAD

**Issue by rdevon** [nipy/nipy#325]
It appears that in:
labs/datasets/volumes/volume_img.py line 280:
pixdim = np.diag(A)
needs to be
pixdim = np.diagonal(A).copy()

"pixdim[0] = -pixdim[0]" threw a warning on earlier versions of numpy (1.8), but breaks outright in 1.9.

**Comment by crcox** [comment]
Just wanted to mention that this problem seems to still exist. I installed NiPy with pip and ran into exactly rdevon's error. Installed from the master branch on the repo, and the error goes away.

**Comment by GaelVaroquaux** [comment]
Hi,

We are progressively advising people to use the nilearn plotting
function, that are similar to the nipy ones, but benefit from a more
modern codebase and more maintenance.
http://nilearn.github.io/auto_examples/index.html#manipulating-images-and-visualization
http://nilearn.github.io/building_blocks/plotting.html

If you find any problems with these, don't hesitate to report problems on
the nilearn issue tracker.

**Comment by rdevon** [comment]
crcox: if you need it to work under nipy, with pip install: 
pip install git+https://github.com/nipy/nipy.git

**Comment by crcox** [comment]
Sorry for never coming back to thank you both for the advice! Best.

**Comment by bcipolli** [comment]
This error still exists. Either it needs to be fixed, or this function needs to be deprecated and/or removed. This is a blocking bug--severe!

If I submit a PR, will someone review it?

**Comment by bthirion** [comment]
I can review it if needed.

**Comment by bcipolli** [comment]
Sorry for the confusion. This looks like it was fixed by @GaelVaroquaux  in 548f0890813a11ba5edf9239bae2ececc3549bd3 . Just hasn't been released.

**Comment by matthew-brett** [comment]
Fixed in master I believe - so closing - please re-open if you disagree.
