### ISSUE TITLE
Installation error with anaconda

### ISSUE THREAD

**Issue by sealhuang** [nipy/nipy#330]
Hi, 

I try to install nipy with anaconda using pip, however an error has occurred which informs a missing `lmkl_lapack95_lp64`. Is there a way to solve the problem?

Best regards.

**Comment by matthew-brett** [comment]
Sorry to be slow to get back to you.  Would you mind trying the latest master branch?

```
pip install git+git://github.com/nipy/nipy.git
```

Does that work for you?

**Comment by satra** [comment]
this was fixed via #372
