### ISSUE TITLE
magic error

### ISSUE THREAD

**Issue by dgwakeman** [nipy/nipy#335]
Hi,
Just cross-posting about an error in nipy when writing files. Not sure if you are subscribed to freesurfer mailing list. Link below
HTH
d

http://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg41673.html

**Comment by matthew-brett** [comment]
Thanks for pointing that out - I just subscribed and posted asking for help replicating...

**Comment by matthew-brett** [comment]
After some more emails on the freesurfer list, and some private emails, it looks as if the OP can't replicate this error, with nibabel 1.3 or current nibabel, so closing for now.  Dan - if you see this come up again, please re-open?
