### ISSUE TITLE
MNI/Talairach coordinate transforms

### ISSUE THREAD

**Issue by effigies** [nipy/nipy#336]
Would nipy be an appropriate place to have coordinate transforms, in particular between MNI and Talairach? These functions are available for MATLAB, related to activation likelihood estimation analyses. Though there doesn't yet seem to be an ALE package for Python, these seem like basic neuroscience/neuroinformatics functions that would be good to have available somewhere.

MATLAB references:
- http://www.brainmap.org/icbm2tal/
- http://imaging.mrc-cbu.cam.ac.uk/imaging/MniTalairach#Doing_better_then_mni2tal

If maintainers are interested, I think I could code up a PR, but would like advice on where these functions would fit.

**Comment by matthew-brett** [comment]
I think it would be a good idea to have them somewhere.

I'm not sure if nibabel or nipy is better - maybe ask on the list.

I have strong views on the icbm2tal transform ...
