### ISSUE TITLE
nipy.algorithms.statistics.empirical_pvalue: returns same theta for different alphas

### ISSUE THREAD

**Issue by ilogue** [nipy/nipy#337]
Hi all,

I'm trying to determine a corrected threshold for my data. I've found that the code below returns the same number (~3.03) for different values of alpha. Does this make sense? The data consist of z/t scores ranging from -2.5 to about 6.5

```
from nipy.algorithms.statistics.empirical_pvalue import NormalEmpiricalNull

enn = NormalEmpiricalNull(data)
theta05 = enn.threshold(alpha=0.05, verbose=True)
theta01 = enn.threshold(alpha=0.01, verbose=True)
theta005 = enn.threshold(alpha=0.005, verbose=True)
theta001 = enn.threshold(alpha=0.001, verbose=True)
```

**Comment by matthew-brett** [comment]
@bthirion - is this one yours?

**Comment by bthirion** [comment]
Yes, I replied. It looks like I did it wrong, since this does not show up in the interface. For the sake of completeness, I'm going to re-post my answer.

**Comment by bthirion** [comment]
In short: I don't reproduce the bug, so I can't help much without access to the data.

Examples: The following script

import numpy as np
from nipy.algorithms.statistics.empirical_pvalue import NormalEmpiricalNull

data = np.random.randn(1000)
data[:100] += 4  # make the data roughly stributed between -2.5 and +6.5
enn = NormalEmpiricalNull(data)
for alpha in [0.05, .01, 0.005, .001]:
    print enn.threshold(alpha=alpha, verbose=True)

yields (given the random draws, do not expect to reproduce these values precisely):
2.04025598294
2.5876695846
2.72737100845
3.1253827127

**Comment by ilogue** [comment]
Thanks for looking at this. I've emailed you a data file on your inria address, @bthirion.

Here is my code
```
import nibabel, numpy
from nipy.algorithms.statistics.empirical_pvalue import NormalEmpiricalNull


fpath = 'nentest.nii.gz'
img = nibabel.load(fpath)
nonNanData = numpy.nan_to_num(img.get_data())
enn = NormalEmpiricalNull(nonNanData)
for alpha in [0.05, .01, 0.005, .001]:
    print(enn.threshold(alpha=alpha, verbose=True))
```
4.26151709172
4.26151709172
4.26151709172
4.26151709172

**Comment by bthirion** [comment]
OK, I see the point. Assuming that you have nilearn installed (if it's not the case, please do it)

from nilearn.input_data import NiftiMasker
import matplotlib.pyplot as plt

x = NiftiMasker(mask_strategy='background').fit_transform('nentest.nii.gz')
plt.figure()
plt.hist(x.ravel(), bins=20)
plt.show()

Then you have this histogram, that essentially shows that this histogram is reduced to the right tail, meaning that the image has already been fitted. based on this, the EmpiricalNull of nipy tries to fit a Gaussian distribution to the data, but as you can guess, this is wrong. Any p-value produced by the EmpiricalNull is bound to be wrong.

Please re-run on an unthresholded image.
Best.

**Comment by ilogue** [comment]
Thanks @bthirion. I'm not sure I understand entirely. You're saying my data are not suitable for this method? They have not been thresholded before. They are (one-sided) z-scores from a permutation test.  Is there another way to figure out an FDR threshold for this data?

**Comment by bthirion** [comment]
Hi @llogue. When I open your image with FSLView if find 0 almost everywhere. Maybe you didn't send me the right image ? Best,

**Comment by ilogue** [comment]
No, this is correct. To improve performance, the analysis is only run on voxels for which sufficient data is available, the others are set to 0. Does this preclude using FDR?

**Comment by bthirion** [comment]
Indeed, you can certaily not use the fdr that requires considering the p-values of all the tests. 

Bertrand 

----- Mail original -----

**Comment by ilogue** [comment]
Okay, thanks for explaining
