### ISSUE TITLE
Zero test coverage on Python 3.x

### ISSUE THREAD

**Issue by bcipolli** [nipy/nipy#338]
The build fails in the setup stage:

![image](https://cloud.githubusercontent.com/assets/4072455/9443758/c5cde1c2-4a37-11e5-999c-508b3e6bacf2.png)

**Comment by bcipolli** [comment]
Running pip with `-vvv`, it looks like the `whl` files are thought to be incompatible with the Python version. I have no idea how it tries to detect this.

![image](https://cloud.githubusercontent.com/assets/4072455/9444283/931247a2-4a3a-11e5-8ddd-98739451ae69.png)

**Comment by matthew-brett** [comment]
I'm trying to fix these over at https://github.com/nipy/nipy/pull/341

**Comment by matthew-brett** [comment]
Closed by #341
