### ISSUE TITLE
How to specify path for data/templates?

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/nipy#379]
When building RPM I need to specify data/templates path. How I can do this?

**Comment by matthew-brett** [comment]
I think you can do this with the environment variable NIPY_DATA_PATH set to point to a directory that contains directory ``nipy/templates`` with the unpacked data package.  Does that work?

https://github.com/nipy/nibabel/blob/master/nibabel/data.py#L159

**Comment by ignatenkobrain** [comment]
Thanks!
