### ISSUE TITLE
Problem with portalocker.py lock acquisition

### ISSUE THREAD

**Issue by falesclf** [nipy/nipy#386]
Hi Nipy folks:

I'm trying to use C-PAC for neuroimaging analysis, and it makes calls to portalocker.py. This routine calls fcntl.flock(...), which I gather means using f-lock processing. This doesn't work in our system, where we have NFS v3 and v4 in use (depending on server). When you run it, you get lock exception 37 ("no lock available").  Various web commentators suggest using fctnl locking instead of flock. Does this sound correct?

Have other users encountered the problem and do you have a fix?

I have spoken to the C-PAC developers and they tell me I can make fixes to portalocker.py myself. According to the website "http://issues.roundup-tracker.org/issue1063890", it is a matter of telling portalocker to use the fctnl.lockf locking mechanism rather than  fctnl.flock. The commenter on this website (named moraes) attaches a patch for this, but I confess I'm not sure how to use the patch, as I assume the symbols + and - at the beginning of many lines are telling me something. Could you tell me how the "elif" code (starting at line 111) should read, in order to substitute the implement the desired locking mechanism?

In case helpful, I'm appending the text to our current portalocker.py version.

Thanks very much for your help.
Sincerely, Christina Fales (falesclf@gmail.com)

---
# portalocker.py - Cross-platform (posix/nt) API for flock-style file locking.
# Requires python 1.5.2 or better.

'''Cross-platform (posix/nt) API for flock-style file locking.

Synopsis:

   import portalocker
   file = open('somefile', 'r+')
   portalocker.lock(file, portalocker.LOCK_EX)
   file.seek(12)
   file.write('foo')
   file.close()

If you know what you're doing, you may choose to

   portalocker.unlock(file)

before closing the file, but why?

Methods:

   lock( file, flags )
   unlock( file )

Constants:

   LOCK_EX
   LOCK_SH
   LOCK_NB

Exceptions:

```
LockException
```

Notes:

For the 'nt' platform, this module requires the Python Extensions for Windows.
Be aware that this may not work as expected on Windows 95/98/ME.

History:

I learned the win32 technique for locking files from sample code
provided by John Nielsen nielsenjf@my-deja.com in the documentation
that accompanies the win32 modules.

Author: Jonathan Feinberg jdf@pobox.com,
        Lowell Alleman lalleman@mfps.com
Version: $Id: portalocker.py 5474 2008-05-16 20:53:50Z lowell $

'''

**all** = [
    'lock',
    'unlock',
    'LOCK_EX',
    'LOCK_SH',
    'LOCK_NB',
    'LockException',
]

import os

class LockException(Exception):
    # Error codes:
    LOCK_FAILED = 1

if os.name == 'nt':
    import win32con
    import win32file
    import pywintypes
    LOCK_EX = win32con.LOCKFILE_EXCLUSIVE_LOCK
    LOCK_SH = 0 # the default
    LOCK_NB = win32con.LOCKFILE_FAIL_IMMEDIATELY
    # is there any reason not to reuse the following structure?
    __overlapped = pywintypes.OVERLAPPED()
elif os.name == 'posix':
    import fcntl
    LOCK_EX = fcntl.LOCK_EX
    LOCK_SH = fcntl.LOCK_SH
    LOCK_NB = fcntl.LOCK_NB
else:
    raise RuntimeError, 'PortaLocker only defined for nt and posix platforms'

if os.name == 'nt':
    def lock(file, flags):
        hfile = win32file._get_osfhandle(file.fileno())
        try:
            win32file.LockFileEx(hfile, flags, 0, -0x10000, __overlapped)
        except pywintypes.error, exc_value:
            # error: (33, 'LockFileEx', 'The process cannot access the file because another process has locked a portion of the file.')
            if exc_value[0] == 33:
                raise LockException(LockException.LOCK_FAILED, exc_value[2])
            else:
                # Q:  Are there exceptions/codes we should be dealing with here?
                raise

```
def unlock(file):
    hfile = win32file._get_osfhandle(file.fileno())
    try:
        win32file.UnlockFileEx(hfile, 0, -0x10000, __overlapped)
    except pywintypes.error, exc_value:
        if exc_value[0] == 158:
            # error: (158, 'UnlockFileEx', 'The segment is already unlocked.')
            # To match the 'posix' implementation, silently ignore this error
            pass
        else:
            # Q:  Are there exceptions/codes we should be dealing with here?
            raise
```

elif os.name == 'posix':
    def lock(file, flags):
        try:
            fcntl.flock(file.fileno(), flags)
        except IOError, exc_value:
            # The exception code varies on different systems so we'll catch
            # every IO error
            raise LockException(*exc_value)

```
def unlock(file):
    fcntl.flock(file.fileno(), fcntl.LOCK_UN)
```

if **name** == '**main**':
    from time import time, strftime, localtime
    import sys
    import portalocker

```
log = open('log.txt', 'a+')
portalocker.lock(log, portalocker.LOCK_EX)

timestamp = strftime('%m/%d/%Y %H:%M:%S\n', localtime(time()))
log.write( timestamp )

print 'Wrote lines. Hit enter to release lock.'
dummy = sys.stdin.readline()

log.close()
```

**Comment by matthew-brett** [comment]
I'm really sorry if I missed it - but are you suggesting a change to nipy somewhere?  I'm afraid I don't personally know `portalocker`.

**Comment by satra** [comment]
@falesclf - if you are using C-PAC this is likely an issue with nipype. could you please close this and post the corresponding issue on the nipype issues.

also portalocker is only used if you log the output to a common shared location. you can disable logging and then portalocker will not be used.

**Comment by falesclf** [comment]
I'm not really familiar with nipy at all. I was just told that the author
of portalocker.py was probably associated with nipy.

But honestly I'm not sure it has to be the actual author. I think I just
need to change a couple of lines of code, and would love to get help from
someone who is python-savvy and knows abotu the two locking mechanisms.

Or maybe just hints on how to translate the patch into usable code in
portalocker. Any chance of finding that kind of guidance?

-Christina

**Comment by falesclf** [comment]
Hi Satrajit:

I'm feeling a little dumb here... I thought nipy was just the parent for
Nipype. No?

-christina

**Comment by satra** [comment]
@falesclf - as a community yes, but as a software the nipy library is as standalone in the community as nipype (although we do have interfaces in nipype that use nipy).

**Comment by matthew-brett** [comment]
Not dumb, it is confusing.  Nipy is both the umbrella organization and a particular project in the umbrella organization.   Here you're on the issue tracker for the `nipy` *project*.  It sounds as if you need the nipype issue tracker at https://github.com/nipy/nipype/issues .  Nipype is another project under the nipy umbrella.

**Comment by matthew-brett** [comment]
OK to close this one @falesclf ?

**Comment by falesclf** [comment]
Yes, although I never got any help with it... I even forget now how I
worked around it. I think our file systems were inconsistent.

Anyway, fine to close the request.
-Christina Fales

**Comment by matthew-brett** [comment]
Thank you for the update - sorry that it didn't resolve in a clear way.
