### ISSUE TITLE
`get_data_light` used but missing

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipy#388]
The function `get_data_light` is used by a number of scripts shipped with nipy (e.g. [this one](https://github.com/nipy/nipy/blob/master/examples/labs/need_data/glm_beta_and_variance.py), which I am currently trying to run). 

The function is however not shipped with nipy, not is it (or the files it should be pointing me to, `s12069_swaloc1_corr.nii.gz` and `localizer_paradigm.csv`) shipped with either nipy-data or nipy-templates.

How can I get the data (and function) needed to run this example?

**Comment by TheChymera** [comment]
Ok, I solved this myself. The `get_data_light` function is located in the same directory as the example functions, just that setup.py seems to not select those files for installation. I was able to use the function (and get the data I needed) by adding the path of the respective subdirectory of my nipy fork to the pythonpath (in the file):


```
import sys
sys.path.append("/home/chymera/src/nipy/examples/labs/need_data/")
```

**Comment by bthirion** [comment]
Dear Chirstian, 

You can now find most of that stuff in Nistats. Beware that Nipy is no longer developed. 
Best, 

Bertrand
