### ISSUE TITLE
test fail on ubuntu 14.04.3

### ISSUE THREAD

**Issue by jongchul** [nipy/nipy#391]
Hi.

I've been playing with nipy to get to know more about neuro-imaging analysis, I mean fMRI.

The reason I start with nipy is because of google search result.  Anyway, it dose not seem to be go smooth for me. 

I've got error during the below test as attached file. 

python -c "import nipy; nipy.test()" 

![test_ubuntu](https://cloud.githubusercontent.com/assets/6112016/12297064/a57cd70c-ba4e-11e5-9274-1f332355a307.jpg)

I installed according to the installation guide. Do I miss something? 
https://github.com/nipy/nipy

**Comment by matthew-brett** [comment]
How did you install exactly?   If you are on Ubuntu, I would expect that you installed using http://neuro.debian.net .  What versions of Python and nipy do you have?

```
python --version
python -c 'import nipy; print(nipy.__version__)'
```

**Comment by jongchul** [comment]
Hi.

I didn't use  http://neuro.debian.net.  

I will try that. 

Thanks.

   

I will inform you
