### ISSUE TITLE
Some issues with coloring in plot_map

### ISSUE THREAD

**Issue by alexvicegrab** [nipy/nipy#405]
I'm using the viz module to visualise some FSL FIRST segmentations, and the cmap (colourmap) works well when I include most of the structures, but when I include a reduced number (3 or less unique values), they all turn white. This is despite inputting the pyplot colormap option "cmap=viz.cm.cold_hot" to plot_map.

I have tried the following example as well:

http://nipy.org/nipy/labs/viz.html

and the red square appears white on my interface, with or without the cmap option.

For reference, I'm plotting on a Jupyter [iPython] Notebook on an Ubuntu system sitting on AWS.

**Comment by alexvicegrab** [comment]
Curiously, the example works perfectly when I run it as a stand-alone python script.

**Comment by alexvicegrab** [comment]
In both cases (iPython and standalone), the viz cmaps only show up in white when there is a restricted number of colours. Any help on correctly using the cmap option would be very helpful.

**Comment by bthirion** [comment]
Dear Sasha,

This code is deprecated. Please use nilearn.plotting instead.
Best,

Bertrand Thirion

**Comment by alexvicegrab** [comment]
Thank you, Bertrand, that's very helpful!

**Comment by matthew-brett** [comment]
@alexvicegrab - would you mind posting an IPython notebook showing the problem (along with the data needed to run it)?  I'd like to fix this in nipy if possible.
