### ISSUE TITLE
SpaceTimeRealign/Realign4d TR

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipy#409]
I noticed that SpaceTimeRealign/Realign4d really *really* want to be given a tr value explicitly, and if none is given [they fail](https://github.com/nipy/nipy/blob/master/nipy/algorithms/registration/groupwise_registration.py#L742).

I wonder why.
TR is contained in the NIfTI header.
I'm not necessarily protesting that the user has the choice to override (rather than fix) a bad header - but shouldn't at least the header be used if the user specifies no value?

I can write a fix for this if you would pull.

**Comment by matthew-brett** [comment]
The problem is that the TR is often not contained in the NIfTI header.  It might be a default value like 0 in which case that's obvious, or a default value like 1, in which case it's not obvious.  So we'd need to decide some policy about when the TR value in the header is intentional vs accidental.

**Comment by TheChymera** [comment]
I'd say unless the header value will lead to an inevitable exception further down the line (which I assume is the case for 0) taking it will be better than raising an error.

So I would propose the following policy:

* prefer the user-specified value, if None read from header
* raise an exception if the header value is 0

I don't think it's a good "feature" to make a function fail when it doesn't have to just because we suspect some users might not be entirely familiar with their data.
If anything we should print a warning, but I doubt that the people who are unaware of whether or not their headers are broken will be reading through the nipype output.

Not least of all - does Realign4d only work with 4d data? whether or not it accepst multiple dimensions will determine how best to read TR from the header.

**Comment by matthew-brett** [comment]
The key thing for me is that it's not at all easy to get an answer you didn't intend.  Clearly 0 is wrong, and we can raise an error.   On the other hand, it's not clear whether 1 is wrong or not.  It could be the correct TR or it could be a default written into the header by software that didn't know the TR, or (if I remember right) the default value filled in by Nipy.   It would be very easy not to notice this and get a result you didn't intend.

**Comment by TheChymera** [comment]
I don't think we should operate under the assumption that some value is invalid, just because people might not notice mistakes. If the value works, I think the reasonable assumption is that it is for real. I, for one, mainly use TR=1

Also, from what I have seen, if people are dealing with malformed headers, they always look to define TR explicitly. If they don't look to do that, it means they trust in their headers.

**Comment by alexis-roche** [comment]
Hi Christian,

This brings us back to a discussion we had a while ago. We did consider the
policy you are suggesting, however it is a fact that the tr filled in the
nifti header cannot always be trusted and we thought it would just make
things confusing to try and guess whether tr is correct or not based on its
value. Failing to notice mistakes is unfortunately common and can have long
term consequences that are way more unpleasant than the pain of checking
some parameters manually.

Also, I wonder if there is a standard way to encode slice times in the
nifti header (honestly I don't know) but in general these are provided by
the user too and need be checked very carefully. Assuming a default slice
order may not be a good policy either.

Alexis

Le 8 sept. 2016 4:06 AM, "Horea Christian" <notifications@github.com> a
écrit :

**Comment by TheChymera** [comment]
@alexis-roche There is, but I think the TR is a considerably easier first step.

As for the general question, I maintain that this issue is confusing the purpose of an error with the purpose of a warning. I think deliberately making the program crash because we assume our users will **neither** provide properly formatted input **nor** read the warnings is a design choice which we should correct.

**Comment by alexis-roche** [comment]
@TheChymera I personally don't feel strongly against issuing a warning rather than raising an error in this specific case. 
@matthew-brett error or warning?

**Comment by matthew-brett** [comment]
I think warnings are largely pointless - most people do not read them.

Our task here is to think of some way that a user can signal that 1.0 is a valid TR, not a placeholder.  For example:

```
In [1]: import nibabel as nib
In [3]: import numpy as np
In [4]: data = np.zeros((2, 3, 4, 5))
In [6]: img = nib.Nifti1Image(data, np.eye(4))
In [7]: img.header['pixdim']
Out[7]: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)
In [8]: nib.save(img, 'test.nii')
In [9]: img_back = nib.load('test.nii')
In [10]: img_back.header['pixdim']
Out[10]: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)
```

**Comment by TheChymera** [comment]
@matthew-brett could you explain what the above snippet is supposed to demonstrate?

**Comment by matthew-brett** [comment]
That the default TR for a nibabel image is 1.

**Comment by TheChymera** [comment]
Which I guess they are doing because it's a best guess if no info is explicitly given. Why should nipy not do the same?

**Comment by matthew-brett** [comment]
The point is that I wanted to avoid using a best guess, when the best guess is generally unlikely to be right:

```
$ python -c 'import this' | grep guess
```

**Comment by TheChymera** [comment]
That's a nice quote, and I do think I understand where you stand on this. But it still seems to me that this design accommodates misuse more than actual use. The function requires users to hard-code TR into pipelines or workflows -or otherwise write a convenience function to "explain" the NIfTI header to a piece of software that has every capability to understand the NIfTI header.

If the function is reading in NIfTI, it should have the capacity to use all the information therein. I feel this is a bit like having a function that takes as a positional argument a dictionary, and then has a keyword argument called `the_actual_value_for_key_A_in_the_dictionary`. Not only that, but in this case we are refusing to consider the value passed with the dictionary.

**Comment by matthew-brett** [comment]
How about a compromise.  We allow None as the TR value.   If tr=None, we look to see if the TR is anything other than exactly 1 or 0 in all of the passed images; if so, we accept that value.    Otherwise we raise an error insisting that the user specify the value.

For people with TR values of exactly one, we suggest that they rewrite their headers with a TR value of 1 + eps.

**Comment by TheChymera** [comment]
what is eps?

**Comment by matthew-brett** [comment]
Sorry - it is 'Machine epsilon' : http://matthew-brett.github.io/teaching/floating_error.html#machine-epsilon

As the pixdim values are float32 in the header, the actual number will be `1 + np.finfo('f4').eps` ~ 1 + 10 ** -7

**Comment by matthew-brett** [comment]
Meaning that, if you have a scan with 1000 volumes at TR of 1, then the last volume onset time will be off by 0.1 milliseconds.

**Comment by TheChymera** [comment]
ok, I'm happy that we can agree on giving users of TR=1 the possibility to select from the header. I fear however that this proposed fix is creating a bigger issue.

Instead of writing a convenience function to help `SpaceTimeRealign()` along, the user now has to hack his preprocessing elsewhere (because obviously ~nobody's raw data says `TR=1+10e-7`). The NIfTI specification does not indicate that if you mean TR=1 you should say TR=1+10e-7 because this is the hack that some people are using to protect you from yourself. So proper preprocessing functions will need to be "broken" just because we are worried about broken preprocessing functions.

Let me try to suggest another compromise:
We allow the TR argument to be `str` as well. if it reads `"header"`, we dynamically get TR from the header. All else stays the same.

**Comment by matthew-brett** [comment]
An alternative is to allow None for 'try and get a believable TR from the header', as above, and also allow `tr` to be a string, where the `header_11` means 'get the TR from the header, but explicitly also allow 1 as a valid value'.

However, I still worry that this will get blindly copied across to pipelines where the TR value of 1 was not meant to be there.

**Comment by TheChymera** [comment]
> However, I still worry that this will get blindly copied across to pipelines where the TR value of 1 was not meant to be there.

I think taking a string TR is already going over and beyond to allow for **incorrect** usage. If someone passes arguments they do not understand I think they are far beyond our help (what would prevent them from copying TR=2 or TR=n which is defined wherever?), and I am sorry to say but I would expect such user's analysis to be iredeemably flawed independently of nipy. I don't see Python APIs being built *around* popular mistakes - like raising an exception if people passed `(10)` , because they might have meant `(10,)`.

**Comment by matthew-brett** [comment]
The point is to make people go significantly out of their way to make an obvious and common error.

**Comment by TheChymera** [comment]
I think having the awkward `"header_11"` or `"from_nifti_header"` value passed explicitly to your function is going very far out of your way. Also there should be a limit to how many hoops we set up. After all, they apply to and impede all users. I think it's poor style to have a function fail and pretty much tell you "I don't believe you" after you explicitly passed it a value.

**Comment by matthew-brett** [comment]
I hear you, but I think there are two levels to believe here.

The first is "I want you to get any reasonable value out of the header". 

The second is "I want to any value at all out of the header, even if it has a high probability of being incorrect due to default in some software writing images".  If you say exactly that, I'll believe you too.

But, I would not expect the first one to include the second, by default.  The second is sufficiently dangerous that I want you to look me in the eye and say, it's all right, I know exactly what I'm doing.

So here's my current offer.  `tr='header'` allowed and `tr=header-allow-1.0` also allowed with the first and second meanings respectively.

**Comment by TheChymera** [comment]
Deal.

What's the best place to drop my code in? SpaceTimeRealign or Realign4d?

**Comment by matthew-brett** [comment]
Good doing business with you :) .  Realign4d looks like the right place.   For testing, it would be good to have a standalone routine that took the `images` argument and returned a common TR or None, if the TR is not the same for each image.

**Comment by TheChymera** [comment]
> a standalone routine

You mean an independent function - neither under SpaceTimeRealign nor Realign4d (but still inside nipy/algorithms/registration/groupwise_registration.py) ?

**Comment by matthew-brett** [comment]
Right.  No big deal, just a suggestion.

**Comment by TheChymera** [comment]
I finished writing this, but it would be better to transfer the behaviour of tr="header" to tr=None. Since we are catching both 1 and 0 here, there's no advantage left to raising an error. This also seems in line with what you said earlier

> If tr=None, we look to see if the TR is anything other than exactly 1 or 0 in all of the passed images; if so, we accept that value.

**Comment by matthew-brett** [comment]
I don't have a strong view whether we should use `tr=None` or `tr='header'` for the case that catches 0 and 1 - your call.  I mean, if you prefer 'header', then we wouldn't allow None.
