### ISSUE TITLE
Link in NiPy documentation incorrect

### ISSUE THREAD

**Issue by kgeier** [nipy/nipy#428]
The NiPy.org website gives download instructions for Windows. However the link to download Python (X, Y) bizarrely takes you to a website about roofing and IT careers. Perhaps this is a joke? Anyway it may be better to use an alternative link with the download immediately available. 

Instruction page: http://nipy.org/nipy/users/installation.html 
Link provided: http://www.pythonxy.com/
Suggested alternative link: https://python-xy.github.io/downloads.html

Thanks!

**Comment by matthew-brett** [comment]
Thanks for noticing that - I fixed it with d09cb68 . Rebuilding the docs now.

**Comment by matthew-brett** [comment]
OK to close this one @kgeier ?

**Comment by kgeier** [comment]
Yup sorry!
