### ISSUE TITLE
Installation Problem on the Ubuntu16

### ISSUE THREAD

**Issue by dongchaoanderuni** [nipy/nipy#432]
According to the guidance, I have installed the nipy on the Mac 10.12. But when I install it on the Ubuntu16 with Python 3.6 according to the web http://nipy.org/nipy/users/installation.html.  I have download the package. But when I test it with the command python -c "import nipy; nipy.test()" . It told me:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named nipy
So,should I add the path of nipy to python? I have already install Anaconda. And linked it to Pycharm. How could I add the nipy's path to use it?

**Comment by matthew-brett** [comment]
Just to check - you did `pip install --user nipy` and that worked correctly without error?

**Comment by dongchaoanderuni** [comment]
Yes, I have checked the information about the nipy.
But when I nus the test command python -c "import nipy; nipy.test()" . It's failed
Requirement already satisfied: nipy in ./nipy
Requirement already satisfied: nibabel>=1.2 in ./.local/lib/python3.5/site-packages (from nipy)
Requirement already satisfied: sympy>=0.7.0 in ./.local/lib/python3.5/site-packages (from nipy)
Requirement already satisfied: numpy>=1.7.1 in ./.local/lib/python3.5/site-packages (from nibabel>=1.2->nipy)
Requirement already satisfied: mpmath>=0.19 in ./.local/lib/python3.5/site-packages (from sympy>=0.7.0->nipy)

**Comment by matthew-brett** [comment]
It looks like you have somehow got a 'nipy' directory, maybe in your home directory?  If so, try deleting that, then `pip install --user nipy` again.

**Comment by dongchaoanderuni** [comment]
I have use command "-rm rf nipy" delete the nipy part, and reinstalled, but it still:
Traceback (most recent call last):
File "", line 1, in
ImportError: No module named nipy

**Comment by matthew-brett** [comment]
So, from the bash shell, try this:

```
mkdir nipy-tmp
cd nipy-tmp
pip install --user nipy
which python
which pip
python -c 'import nipy'
```

What do you get? (full output of the commands above).

**Comment by dongchaoanderuni** [comment]
Very thankful. It's very kind of you.Now, it worked. But when I use the test part. It give me the feedback.
Ran 1169 tests in 3.263s
FAILED (SKIP=2, errors=34, failures=2)
when I use pycharm to edit the python document. It is said.
No module named 'nipy.testing'; 'nipy' is not a package
But when I did all of this on Mac, it worked.

**Comment by yarikoptic** [comment]
FWIW, if you just want to have it installed, you could just `apt-get install python-nipy` from the NeuroDebian repository.  We do carry a build for the 16.x http://neuro.debian.net/pkgs/python-nipy.html

**Comment by matthew-brett** [comment]
OK to close this issue @dongchaoanderuni ?
