### ISSUE TITLE
 Test failures with `TypeError: constructor returned NULL` 

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipy#444]
I am [still](https://github.com/nipy/nipy/issues/443) trying to run the tests on `=nipy-0.4.2`, and I am now confronted with a series of `TypeError: constructor returned NULL`:

http://bpaste.net/show/ac201a7ced08

It seems these are the only errors still happening. Can you help me straighten this aout?
As before the build log is included in the link.

**Comment by matthew-brett** [comment]
You're trying to use the matplotlib GDK backend, without a display.  Before the tests, in the directory from which you run the tests, run this:

```
echo "backend : agg" > matplotlibrc
```

This sets matplotlib to use a not-interactive display.

You'll likely run into other test problems, have a look at `tools/nipnost` for the testing rig we use.

**Comment by TheChymera** [comment]
Thank you! No tests error any more.
