### ISSUE TITLE
ImportError: cannot import name 'factorial' from 'scipy.misc'

### ISSUE THREAD

**Issue by jcohenadad** [nipy/nipy#453]
it looks like there are new deprecations which cause issues in nipy imports. When running in `0.4.2`:
~~~
pip install nose mock
python -c "import nipy; nipy.test()"
~~~
I get:
~~~
ImportError: cannot import name 'factorial' from 'scipy.misc'
~~~

Which seems to be caused by:  https://scipy.github.io/devdocs/release.1.3.0.html#scipy-interpolate-changes

**Comment by jcohenadad** [comment]
Another one: `AttributeError: module 'scipy.misc' has no attribute 'comb'`

I've started to work on a fix: https://github.com/jcohenadad/nipy

**Comment by keiichiiownsu12** [comment]
The factorial function in scipy 1.3.0 onwards is located in scipy.special

Changing the 
```from scipy.misc import factorial```
to 
```from scipy.special import factorial```

in files such as 
.../lib/python3.x/site-packages/nipy/algorithms/registration/histogram_registration.py

Although now I am getting a few new errors. . .most recently in 
.../lib/python3.x/site-packages/nipy/algorithms/registration/histogram_registration.py :
```File ".../lib/python3.x/site-packages/nipy/algorithms/registration/histogram_registration.py", line 208, in _set_similarity
    raise ValueError('similarity should be callable')```

**Comment by jcohenadad** [comment]
@keiichiiownsu12 the fix is already implemented in this PR https://github.com/nipy/nipy/pull/454, waiting to be reviewed by the admins
