### ISSUE TITLE
No module named 'numpy.testing.decorators'

### ISSUE THREAD

**Issue by andyrevell** [nipy/nipy#463]
Hi,

When doing import nipy, I get this error below

![Screenshot from 2020-10-25 21-25-03](https://user-images.githubusercontent.com/43831513/97124962-9613f680-1708-11eb-9de1-9525d4ff959f.png)

here is my conda environment:

![Screenshot from 2020-10-25 21-24-10](https://user-images.githubusercontent.com/43831513/97124928-72e94700-1708-11eb-8623-d23e8287d04e.png)

I have tried different versions of numpy, and it does not work

**Comment by effigies** [comment]
I would imagine numpy 1.15 or so should work. How old did you try?

**Comment by fabioboh** [comment]
with numpy==1.16.4 it works, but not with the latest

**Comment by scarere** [comment]
Can confirm that it also works with 1.17.0, and seems to break with numpy==1.18.

**Comment by effigies** [comment]
At this point, getting nipy back to a trivially installable state is going to be a significant task. If there are people here using it, would any of you be interested in spearheading the effort?

**Comment by matthew-brett** [comment]
This should be fixed in current master.  I'll do a new release soon.

**Comment by scarere** [comment]
Please let me know when the new release is out

**Comment by matthew-brett** [comment]
The release is almost ready - last blocker that I know if is #484 .  If you or anyone has time to review, I'd be grateful.

**Comment by matthew-brett** [comment]
@scarere @jiavila - new release out - 0.5.0.  Please let me know of any problems.
