### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mr-c** [nipy/nipy#464]
Debian would appreciate a proper new release of nipy; it is in danger of being removed from Debian completely (it has already been removed from our testing distribution) 

https://bugs.debian.org/959138

Thanks!

**Comment by effigies** [comment]
@mr-c Does Debian pull from the GitHub archive or from PyPI? And do you know if current master is in a state where it can be packaged for Debian?

**Comment by mr-c** [comment]
Currently we watch for new tags on GitHub, but we can also watch PyPI

https://salsa.debian.org/med-team/nipy/-/blob/master/debian/watch

**Comment by mr-c** [comment]
> And do you know if current master is in a state where it can be packaged for Debian?

If someone cuts and tags a pre-release then I'll upload an updated package to Debian's "experimental" distribution.

**Comment by effigies** [comment]
@mr-c I just tagged 0.4.3rc1.

**Comment by mr-c** [comment]
Thanks @effigies ! I just opened a new issue with the results on my initial attempt at updating the Debian package for 0.4.3rc1: https://github.com/nipy/nipy/issues/466

**Comment by matthew-brett** [comment]
I've just released 0.5.0 - @mr-c - can you check it works for you?

**Comment by mr-c** [comment]
Seems so, though I get an error with building the docs; perhaps because you don't allow the use of a recent sphinx version? Debian is on Sphinx 3.4.3 ; `doc-requirements.txt` lists `sphinx>=1.0,<3.0`

**Comment by matthew-brett** [comment]
See https://github.com/nipy/nipy/pull/485

@mvdoc - did I miss something in allowing updates to Sphinx and Numpydoc?  Sorry, I didn't go back to check what you did before.

**Comment by mr-c** [comment]
Thanks @matthew-brett ; https://github.com/nipy/nipy/pull/485/files#diff-e170e9a7d787c21095c6c11bb25f0f1ff0294a42a46d45ba6fb5ed794e457624R19 is what I also figured out locally

**Comment by mr-c** [comment]
Hmm.. now we can't run `nipy.tests.test_scripts.test_{nipy_3_4,nipy_4d_realign,nipy_tsdiffana,nipy_diagnose}` as `run_command` makes assumptions about the file system layout and overwrites the `PYTHONPATH` we were setting for the running of the tests..

```
======================================================================
ERROR: nipy.tests.test_scripts.test_nipy_4d_realign
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build/nipy/tests/test_scripts.py", line 158, in test_nipy_4d_realign
    run_command(cmd)
  File "/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build/nipy/tests/scriptrunner.py", line 154, in run_command
    raise RuntimeError(
RuntimeError: Command "['nipy_4d_realign', '2.0', '/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build/nipy/testing/functional.nii.gz', '--slice_dim', '2', '--slice_dir', '-1', '--save_path', '.']" failed with
                stdout
                ------
                b''
                stderr
                ------
                b'Traceback (most recent call last):\n  File "/build/nipy-0.5.0/debian/python3-nipy/usr/bin/nipy_4d_realign", line 33, in <module>\n    sys.exit(load_entry_point(\'nipy==0.5.0\', \'console_scripts\', \'nipy_4d_realign\')())\n  File "/build/nipy-0.5.0/debian/python3-nipy/usr/bin/nipy_4d_realign", line 22, in importlib_load_entry_point\n    for entry_point in distribution(dist_name).entry_points\n  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution\n    return Distribution.from_name(distribution_name)\n  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name\n    raise PackageNotFoundError(name)\nimportlib.metadata.PackageNotFoundError: nipy\n'
```

**Comment by mr-c** [comment]
Here is how we invoke the tests:

```
cd debian ; \
NIPY_DEBUG_PRINT=1 PATH=/build/nipy-0.5.0/debian/python3-nipy/usr/bin:$PATH \
  PYTHONPATH=/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build:$PYTHONPATH \
  MPLCONFIGDIR=/build/nipy-0.5.0/build \
  ../tools/nipnost nipy
```

The sample script suceeds when I run it directly 

```
root@mrc-tux:/build/nipy-0.5.0# PATH=/build/nipy-0.5.0/debian/python3-nipy/usr/bin:$PATH   PYTHONPATH=/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build:$PYTHONPATH      MPLCONFIGDIR=/build/nipy-0.5.0/build nipy_4d_realign 2.0 /build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build/nipy/testing/functional.nii.gz --slice_dim 2 --slice_dir -1 --save_path .          
/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build/nipy/io/files.py:145: FutureWarning: Default `strict` currently False; this will change to True in a future version of nipy
  ni_img = nipy2nifti(img, data_dtype = io_dtype)
root@mrc-tux:/build/nipy-0.5.0# echo $?
0
```

**Comment by matthew-brett** [comment]
Is there a reason you can't invoke the tests directly?  Where do the setuptools script files get installed to?

We could force the `scriptrunner` code to not look in the local module for the scripts, and therefore, not modify PYTHONPATH.

**Comment by mr-c** [comment]
> Is there a reason you can't invoke the tests directly?

I thought we were!

> Where do the setuptools script files get installed to?

During package building, they get installed to `debian/python3-nipy/usr/bin`

> We could force the `scriptrunner` code to not look in the local module for the scripts, and therefore, not modify PYTHONPATH.

I added some debugging code and I was wrong; `PYTHONPATH` is being added to, not overwritten. Not sure why it is still failing to find the package though..

``` diff
--- nipy.orig/nipy/tests/scriptrunner.py
+++ nipy/nipy/tests/scriptrunner.py
@@ -146,6 +146,8 @@
                 env['PYTHONPATH'] = self.local_module_dir
             else:
                 env['PYTHONPATH'] = self.local_module_dir + pathsep + pypath
+        if self.debug_print:
+            print(f"PYTHONPATH: {env['PYTHONPATH']}")
         proc = Popen(cmd, stdout=PIPE, stderr=PIPE, env=env)
         stdout, stderr = proc.communicate()
         if proc.poll() is None:
```

```
-------------------- >> begin captured stdout << ---------------------
Running command '['nipy_4d_realign', '2.0', '/build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build/nipy/testing/functional.nii.gz', '--slice_dim', '2', '--slice_dir', '-1', '--save_path', '.']'
PYTHONPATH: /build/nipy-0.5.0/.pybuild/cpython3_3.9_nipy/build:

--------------------- >> end captured stdout << ----------------------
```

**Comment by matthew-brett** [comment]
I think we're ready for a new release now.  I guess 0.6.  Anyone got anything they really want in there?
