### ISSUE TITLE
wrong attribute in sympy 

### ISSUE THREAD

**Issue by fabioboh** [nipy/nipy#467]
File "/usr/local/lib/python3.6/dist-packages/nipy/algorithms/statistics/formula/formulae.py", line 270, in <module>
    class Beta(sympy.symbol.Dummy):
AttributeError: module 'sympy' has no attribute 'symbol'

should that be Symbol or symbols?

which versions I have:

Requirement already satisfied: nipy in /usr/local/lib/python3.6/dist-packages (0.4.2)
Requirement already satisfied: sympy>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from nipy) (1.7.1)
Requirement already satisfied: nibabel>=1.2 in /usr/local/lib/python3.6/dist-packages (from nipy) (2.3.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.6/dist-packages (from sympy>=0.7.0->nipy) (1.1.0)
Requirement already satisfied: numpy>=1.7.1 in /usr/local/lib/python3.6/dist-packages (from nibabel>=1.2->nipy) (1.16.4)

**Comment by matthew-brett** [comment]
I think Matteo Visconti di Oleggio Castello fixed this one with commit d5aece6e ... - do you agree?
