### ISSUE TITLE
`python setup.py clean` requires nibabel

### ISSUE THREAD

**Issue by mr-c** [nipy/nipy#472]
This stings us when us Debian volunteers are trying to build a source package on our personal workstations (where no dependencies besides Python 3 are installed) to build the final binary package in a chroot/container (where all the dependencies are already available)

```
I: pybuild base:232: python3.9 setup.py clean 
Traceback (most recent call last):
  File "/home/michael/debian/nipy/setup.py", line 71, in <module>
    raise RuntimeError(ver_err_msg)
RuntimeError: We need package nibabel, but not importable
```

**Comment by matthew-brett** [comment]
I don't know the Debian process well enough to know if #474 will fix this - but it does move to a more standard setuptools dependency system.
