### ISSUE TITLE
Publish wheels for Python 3.10 and recent versions of macOS

### ISSUE THREAD

**Issue by ghisvail** [nipy/nipy#494]
`nipy` is getting difficult to install on modern [setup](https://github.com/python-poetry/poetry/issues/6279) due to absence of wheels and a build system which is not PEP-518 compliant. Pip will default to it sooner or later, `numpy.distutils` has been officially deprecated and marked for removal for Python 3.12, and core projects like `scipy` have begun their transition (to `meson`in their case).

Since transitioning the build system is not an easy task and may take an undefined amount a time, an alternative would be to regularly produce wheels for supported systems. Right now, were are missing wheels for Python 3.10 for all OS, and for all supported Python versions on macOS Monterey.

Perhaps an additional reason to make a new release (see #464).

Cheers.

**Comment by effigies** [comment]
Nipy is essentially unmaintained. What are people using it for that it's worth updating?

If it's just in the dependency graph for another package and the code is never called outside tests, then it's probably worth making an optional dependency in the downstream tool. If somebody is using it, they might want to consider maintaining.

**Comment by ghisvail** [comment]
> Nipy is essentially unmaintained. What are people using it for that it's worth updating?

For us, it was transitively through `nipype.algorithms.metrics.Similarity`.

> If it's just in the dependency graph for another package and the code is never called outside tests, then it's probably worth making an optional dependency in the downstream tool.

That does not solve the issue of running the tests covering the piece of code using `nipy` though.

> If somebody is using it, they might want to consider maintaining.

We'll probably end up just vendoring the piece of code of interest.

But maybe it's worth puting a disclaimer at the very top of the readme that the project is considered unmaintained / up for adoption. Or even archiving the project.

**Comment by matthew-brett** [comment]
I'll have a look at the wheels at the weekend.
