### ISSUE TITLE
Nipy using deprecated nibabel decorator

### ISSUE THREAD

**Issue by dipterix** [nipy/nipy#505]
```
Error: nibabel.deprecator.ExpredDeprecationError: setattr_on_read has been renamed to auto_attr.
```

I used `pip` to install `nipy`, which automatically gave me nibabel 5.0.1, but this deprecation message prevented me from importing nipy.

I'm using latest miniconda on Windows. Please let me know if more information is needed.

**Comment by musicinmybrain** [comment]
I was looking at the `python-nipy` package in Fedora, which has quite a lot of errors and failures in the tests (with nibabel 5.1.0). I tried applying the linked PR, and got a lot of errors like:

```
nibabel.deprecator.ExpiredDeprecationError: get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj).
* deprecated from version: 3.0
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
```

As an experiment, I tried a totally blind search and replace,

```
find . -type f -name '*.py' -print0 |
  xargs -r -0 -t sed -r -i 's/\bget_data\b/get_fdata/g'
```

and found that got me down to nine errors. Is this what other people are seeing?

**Comment by dipterix** [comment]
Also how can I resolve this issue?

```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by musicinmybrain** [comment]
> Also how can I resolve this issue?
> 
> ```
> AttributeError: module 'numpy' has no attribute 'float'.
> `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> ```

Is this in the latest `master`? Quite a lot of instances of `np.float` were replaced in https://github.com/nipy/nipy/commit/3437e20d201f8fa47bef13f5280b0e0124e8db67.

**Comment by dipterix** [comment]
I just uses `pip install nipy`

**Comment by musicinmybrain** [comment]
> As an experiment, I tried a totally blind search and replace, [...] and found that got me down to nine errors. Is this what other people are seeing?

This is still true. I get `FAILED (errors=77, failures=14)` before the search-and-replace and `FAILED (SKIP=1, errors=8)` after.

I’m not able to audit the resulting diff right now to see if it really makes sense, but I guess I’ll post it as a PR nonetheless.
