### ISSUE TITLE
No longer available in Python 3.12: numpy.distutils

### ISSUE THREAD

**Issue by musicinmybrain** [nipy/nipy#526]
For the [`numpy` 1.26 release](https://github.com/numpy/numpy/releases/tag/v1.26.0), which brings official support for Python 3.12, [`numpy.distutils` is removed entirely in Python 3.12](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration).

This package will need to find a way to eliminate the use of `numpy.distutils`.

**Comment by matthew-brett** [comment]
Yes, I think we'll have to follow scipy, scikit-image, and dipy in adopting Meson.  E.g. https://github.com/dipy/dipy/pull/2715

**Comment by jarrodmillman** [comment]
See #527

**Comment by musicinmybrain** [comment]
I just tested out the latest commit in `main`, e5e063b09d094ff79d2089261828fd2b2c843ab6. After some packaging changes (mostly welcome simplifications!) I’m able to build `nipy` in Fedora Rawhide with:

- Python 3.12.0 (final)
- NumPy 1.26.0
- All tests, including doctests, running and passing with `pytest` and no `nose` or `nose3`

I’m going to keep fussing over packaging details for a while, try things on non-`x86_64` architectures, maybe offer some PR’s to deal with some warnings, and so on, before actually updating the Fedora package. Still, the recent work on this project has been an amazingly successful sprint.

Feel free to close this issue any time you like.

By the way, are you expecting to tag a new release in the moderately near future?

**Comment by matthew-brett** [comment]
Yes, we'll release soon - thanks for pressing us.

**Comment by effigies** [comment]
Closing. #464 tracks the request for a new release.
