### ISSUE TITLE
Work out some way to run benchmarks

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipy#537]
We are about to remove the `.bench()` helper code to run the benchmarks.

It seems these are:

```
$ rg "bench_"
nipy/labs/glm/benchmarks/bench_glm.py
38:def bench_ols_axis0():
42:def bench_ols_axis1():
46:def bench_ols_axis2():
50:def bench_ols_axis3():

nipy/labs/bindings/benchmarks/bench_numpy.py
29:def bench_copy_vector_contiguous():
34:def bench_copy_vector_strided():

nipy/algorithms/statistics/bench/bench_intvol.py
13:def bench_lips3d():
37:def bench_lips2d():
61:def bench_lips1d():
```

I believe all the tests are simple prints of values from functions.  I believe only `nipy/labs/bindings/benchmarks/bench_numpy.py` has timings.

I don't think pytest will collect these functions as tests, no matter what (even with `-k bench`).  Any ideas for running time testing?

**Comment by effigies** [comment]
I think you can write an alternative config file: https://docs.pytest.org/en/stable/example/pythoncollection.html#changing-naming-conventions

```ini
[pytest]
python_files = bench_*.py
python_functions = bench_*
```

**Comment by effigies** [comment]
Call it `bench.ini` and pass `pytest -c bench.ini`?

**Comment by matthew-brett** [comment]
Nice!  Thanks - I'll give that a try.
