### ISSUE TITLE
Supported Python versions?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nipy#557]
I understand nipy supports Python ≥ 3.7:
https://github.com/nipy/nipy/blob/ca70df937b6943d2fbc37b65c463bb78bab28f22/pyproject.toml#L62-L67

However, this is not clearly documented.

Worse, the ruff setting [target-version](https://docs.astral.sh/ruff/settings/#target-version), the minimum Python version to target, is set to Python 3.9:
https://github.com/nipy/nipy/blob/ca70df937b6943d2fbc37b65c463bb78bab28f22/pyproject.toml#L77-L79

How about adding the [`requires-python`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires) key in the [`[project]`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#static-vs-dynamic-metadata) table? As far as I can see, [mesonpy understands it](https://mesonbuild.com/meson-python/tutorials/introduction.html#configuring-our-python-package).

**Comment by effigies** [comment]
The CI only tests down to 3.9, so I suspect we're following SPEC0 and only support 3.9+. In which case we could remove the build requirements for older Python.

I agree that we should specify a requires-python and use classifiers to advertise the intended support range.

**Comment by effigies** [comment]
Tests pass on Python 3.8, but installation fails on Python 3.7. With 3.7 EOL, it doesn't seem worth even a small effort to fix that.
