### ISSUE TITLE
nipy for conda

### ISSUE THREAD

**Issue by drcandacemakedamoore** [nipy/nipy#567]
I noticed the nipy for conda/anaconda is not up to date with more recent releases. When will this happen?

**Comment by effigies** [comment]
It looks like @ocefpaf is packaging it here: https://github.com/conda-forge/nipy-feedstock. That's a question for him.

**Comment by ocefpaf** [comment]
> It looks like @ocefpaf is packaging it here: https://github.com/conda-forge/nipy-feedstock. That's a question for him.

[Please ask in the feedstock](https://github.com/conda-forge/nipy-feedstock). Upstream devs are quite busy already to take care of all the downstream packaging.
