### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipy#583]
We should do a Numpy 2.0 release soon - any blockers?

**Comment by DimitriPapadopoulos** [comment]
Perhaps #584.

**Comment by DimitriPapadopoulos** [comment]
This could be the last release supporting Python 3.8 — it will reach EOL in October.

**Comment by matthew-brett** [comment]
OK - release 0.6.1 done at https://pypi.org/project/nipy/0.6.1/
